batch_size: 4
criterion:
  losses:
  - input_keys:
      input: predicted_image
      target: fixed_image
    loss_name: MSELoss
    loss_parameters:
      reduction: mean
    return_loss: false
    weight: 1.0
  - input_keys:
      pred: predicted_image
      target: fixed_image
    loss_name: L1Loss
    loss_parameters: {}
    return_loss: false
    detach_values: []
    weight: 1.0
dataset:
  im_size: !!python/tuple
  - 1
  - 256
  - 256
  image_keypoints: []
  image_sequences: []
  register_limit: 5
  train: true
  use_crop: false
  use_masks: true
  multiply_mask: true
  
device: cuda:0
expdir: ../DefReg/src
load_epoch: 0
logdir: ../DefReg/logs/test_exp
model:
  image_size: 128
  in_channels: 1
  model_name: DefRegNet
  use_theta: true
  use_diffeomorphic: false
model_name: model
model_path: ''
num_epochs: 100
num_workers: 4
validate_by_points: true
optimizer:
  lr: 0.0001
  name: Adam
  parameters: {}
save_step: 20
savedir: ../DefReg/logs/test_exp
scheduler:
  name: ReduceLROnPlateau
  parameters: {}

tensorboard: true
val_dataset:
  im_size: !!python/tuple
  - 1
  - 256
  - 256
  image_keypoints: []
  image_sequences: []
  register_limit: 5
  train: false
  use_crop: false
  use_masks: true
  multiply_mask: true
